---
title: "FUT2_dietguthealth_fiber"
author: "Yasmine"
date: "`r Sys.Date()`"
output: html_document
---

Purpose: determine associations between secretor status, fiber intake and GI inflammation marker levels. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

```{r import}

# Genotyping 
# fut2 <- read.csv("/Users/yasmine.bouzid/Documents/FUT2_analysis/data/forR_fut2.csv", header = T)
# subset(fut2, select = c(subject_id, ag))

# taxaHFE output 
thfe <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/fut2_taxa_hfe/dietML_microbe.csv", header = T)

# Gut health / dietary data 

df_l <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_l.csv", header = T) # all we need is ID and 3 fiber variables 
df_selected <- subset(df_l, select = c(subject_id, kcal, dt_kcal, fibe, dt_fibe, dt_fiber_sol))



# MEEEERGE 

# df_l <- merge(df_l, fut2, by = "subject_id") # n = 338

df <- merge(df_selected, thfe, by = "subject_id")
rm(df_l, df_selected, thfe)

# unfortunately, need to correct structure of some variables each time -->

df$subject_id <- as.factor(as.character(df$subject_id))
df$sex <- df$sex %>% recode_factor('1' = 'Male', '2' = "Female")

# Replace NA values with a new factor level
df <- df %>%
  mutate(sex = as.character(sex)) %>%  # Convert to character to add a new level
  mutate(sex = if_else(is.na(sex), "Female", sex)) %>%  # Replace NA with the new value
  mutate(sex = factor(sex))  # Convert back to factor

```

Create fiber variables per 1000 kcal 
```{r fiber-per-kcal}

# Create fibe_pk (pk = per 1000 kcal), dt_fibe_pk, dt_fiber_sol_pk

df$fibe_pk <- df$fibe/(df$kcal/1000)

df$dt_fibe_pk <- df$dt_fibe/(df$dt_kcal/1000)

df$dt_fiber_sol_pk <- df$dt_fiber_sol/(df$dt_kcal/1000)


```

```{r separate-ns-s}

# create df with only non-secretors 

df_ns <- df[df$feature_of_interest == "non_secretor", ]
df_s <- df[df$feature_of_interest == "secretor", ]

```



```{r tertile}


# Calculate the tertile cut points
fibe_pk_tertile_cut_points <- quantile(df_s$fibe_pk, probs = c(0, 1/3, 2/3, 1))

# Assign the tertile values to the dataframe
df_s$fibe_pk_tertile <- cut(df_s$fibe_pk, breaks = fibe_pk_tertile_cut_points, labels = c("T1", "T2", "T3"), include.lowest = TRUE)

# Check the result
head(df_s)


# Calculate the tertile cut points
dt_fibe_pk_tertile_cut_points <- quantile(df_s$dt_fibe_pk, probs = c(0, 1/3, 2/3, 1))

# Assign the tertile values to the dataframe
df_s$dt_fibe_pk_tertile <- cut(df_s$dt_fibe_pk, breaks = dt_fibe_pk_tertile_cut_points, labels = c("T1", "T2", "T3"), include.lowest = TRUE)

# Check the result
head(df_s)


# Calculate the tertile cut points
dt_fiber_sol_pk_tertile_cut_points <- quantile(df_s$dt_fiber_sol_pk, probs = c(0, 1/3, 2/3, 1))

# Assign the tertile values to the dataframe
df_s$dt_fiber_sol_pk_tertile <- cut(df_s$dt_fiber_sol_pk, breaks = dt_fiber_sol_pk_tertile_cut_points, labels = c("T1", "T2", "T3"), include.lowest = TRUE)

# Check the result
head(df_s)


```


```{r bind}

missing_cols <- setdiff(names(df_s), names(df_ns))
print(missing_cols)

for (col in missing_cols) {
  df_ns[[col]] <- NA
}

# Ensure the columns are in the same order
df_ns <- df_ns[names(df_s)]

# Print the updated DataFrame 1
print(df_ns)


combined_df <- rbind(df_ns, df_s)

# Print the combined dataframe
print(combined_df)
names(combined_df)

# replace NAs in the tertile columns for non-secretors with NS

# Columns to replace NA values
cols_to_replace <- c("fibe_pk_tertile", "dt_fibe_pk_tertile", "dt_fiber_sol_pk_tertile")
replacement_value <- "NS"  # The value to replace NA with

# Loop through the columns and replace NA values
for (col in cols_to_replace) {
  combined_df[[col]][is.na(combined_df[[col]])] <- replacement_value
  combined_df[[col]] <- as.factor(combined_df[[col]])  # Ensure the column is a factor
}

# Print the result
head(combined_df)



```
```{r write} 

write.csv(combined_df, file = "/Users/yasmine.bouzid/Documents/FUT2_analysis/data/dietML_microbe_wfiber.csv", row.names = F)

```

