---
title: "FUT2_covar_sex"
author: "Yasmine"
date: "`r Sys.Date()`"
output: html_document
---
Purpose: See if there's a difference in proportion of males and females between secretors and non-secretors 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(sjPlot)
library(tidyverse)
library(car)
library(rcompanion)
```

Import / test we have the right ones (stool data cleaning participants removed)

```{r import}

# Genotyping 
fut2 <- read.csv("/Users/yasmine.bouzid/Documents/FUT2_analysis/data/forR_fut2.csv", header = T)

# here's the thing, we should merge onto fut2 since that has the most genotype

# Gut health 

df_l <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_l.csv", header = T)

# MEEEERGE 
df_l <- merge(fut2, df_l, by = "subject_id") # n = 338

table(df_l$secr_status)

# unfortunately, need to correct structure of some variables each time -->

df_l$subject_id <- as.factor(as.character(df_l$subject_id))
df_l$sex <- df_l$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_l$age_cat <- df_l$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_l$bmi_cat <- df_l$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

# READY FOR LIFT OFF
```

Age

```{r separate-test}

# Test differences in mean age between secretors and non-secretors 
# Non-parametric because...not sure whether factor levels normally distributed..guess I could test
# Anyway
# Chi-squared proportion test (create a contingency table)

df <- data.frame(df_l$sex, df_l$secr_status)
df$df_l.secr_status <- as.factor(as.character(df$df_l.secr_status))

# now test 
chi_tbl <- table(df_l$sex, df_l$secr_status)
chisq.test(chi_tbl) # no difference 



tbl <- prop.table(table(df_l$sex, df_l$secr_status), margin = 1)
tbl


# visualize
fig_s2 <- ggplot(df_l, aes(x =secr_status, fill =sex)) +
  geom_bar(position = "fill") + 
  ggtitle("Chi-Square Independence Test (P = 0.66)") +
  xlab("Secretor Status") +
  ylab("Proportion Male vs. Female") +
   scale_x_discrete(
    labels = c("Non-secretors (n = 70)", "Secretors (n = 268)")) +
   scale_fill_brewer(palette = "Set1") +
  labs(fill = "Sex") +
  theme_bw() +
  theme(
    plot.title = element_text(size = 20),
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)) 

ggsave("/Users/yasmine.bouzid/Documents/FUT2_analysis/plots/fig_s2.jpeg", plot = fig_s2, width = 8, height = 6, units = "in")

```



