---
title: "gi_markers_bysecretorstatus_FUT2guthealth"
author: "Yasmine/Danielle"
date: 11/20/2025
Purpose: determine associations between secretor status, fiber intake and GI inflammation marker levels. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r analysis}

# Genotyping 
fut2 <- read.csv("../fut2_data/forR_fut2.csv", header = T)

# Gut health 
df_c <- read.csv("../dietguthealth_data/df_c.csv", header = T)
df_m <- read.csv("../dietguthealth_data/df_m.csv", header = T)
df_n <- read.csv("../dietguthealth_data/df_n.csv", header = T)
df_l <- read.csv("../dietguthealth_data/df_l.csv", header = T)

# MERGE 
df_c <- merge(df_c, fut2, by = "subject_id") # n = 288
df_m <- merge(df_m, fut2, by = "subject_id") # n = 288
df_n <- merge(df_n, fut2, by = "subject_id") # n = 282
df_l <- merge(df_l, fut2, by = "subject_id") # n = 338

# unfortunately, need to correct structure of some variables each time -->

df_c$subject_id <- as.factor(as.character(df_c$subject_id))
df_m$subject_id <- as.factor(as.character(df_m$subject_id))
df_n$subject_id <- as.factor(as.character(df_n$subject_id))
df_l$subject_id <- as.factor(as.character(df_l$subject_id))

#Need to simply check if there is a significant difference in any of the outcomes between
#secretors and non-secretors, independent of dietary intake. 
#Outcomes have already been transformed. And there was no difference in age/sex/bmi between
#secretors and non-secretors, so just using t-tests. 

# Calprotectin
t.test(clpn_ln ~ secr_status, data = df_c)

#Welch Two Sample t-test
#
#data:  clpn_ln by secr_status
#t = -0.13444, df = 107.93, p-value = 0.8933
#alternative hypothesis: true difference in means between group non_secretor and group secretor is not equal to 0
#95 percent confidence interval:
#  -0.2594896  0.2265252
#sample estimates:
#  mean in group non_secretor     mean in group secretor 
#3.674488                   3.690970

pdf(file="../graphs/calp_by_secr_status.pdf")
boxplot(clpn_ln ~ secr_status, varwidth=TRUE, notch=TRUE, data=df_c, ylab="ln-transformed calprotectin", xlab="secretor status")
dev.off()

# Myeloperoxidase
t.test(mpo_ln ~ secr_status, data = df_m)
pdf(file="../graphs/mpo_by_secr_status.pdf")
boxplot(mpo_ln ~ secr_status, varwidth=TRUE, notch=TRUE, data=df_m, ylab="ln-transformed myeloperoxidase", xlab="secretor status")
dev.off()

# Welch Two Sample t-test
#
# data:  mpo_ln by secr_status
# t = -0.65111, df = 93.938, p-value = 0.5166
# alternative hypothesis: true difference in means between group non_secretor and group secretor is not equal to 0
# 95 percent confidence interval:
#   -0.4129407  0.2089931
# sample estimates:
#  mean in group non_secretor     mean in group secretor 
# 5.561350                   5.663324 

# Neopterin
t.test(nptn_boxcox ~ secr_status, data = df_n)
pdf(file="../graphs/nptn_by_secr_status.pdf")
boxplot(nptn_boxcox ~ secr_status, varwidth=TRUE, notch=TRUE, data=df_n, ylab="boxcox-transformed neopterin", xlab="secretor status")
dev.off()

#Welch Two Sample t-test
#
#data:  nptn_boxcox by secr_status
#t = -0.82119, df = 90.558, p-value = 0.4137
#alternative hypothesis: true difference in means between group non_secretor and group secretor is not equal to 0
#95 percent confidence interval:
#  -0.4116435  0.1708510
#sample estimates:
#  mean in group non_secretor     mean in group secretor 
#-0.09163040                 0.02876587 

# LBP
t.test(lbp_ln ~ secr_status, data = df_l)
pdf(file="../graphs/lbp_ln_by_secr_status.pdf")
boxplot(lbp_ln ~ secr_status, varwidth=TRUE, notch=TRUE, data=df_l, ylab="ln-transformed plasma LBP", xlab="secretor status")
dev.off()

#Welch Two Sample t-test
#
#data:  lbp_ln by secr_status
#t = 1.1443, df = 105.83, p-value = 0.2551
#alternative hypothesis: true difference in means between group non_secretor and group secretor is not equal to 0
#95 percent confidence interval:
#  -0.05512275  0.20560143
#sample estimates:
#  mean in group non_secretor     mean in group secretor 
# 2.384675                   2.309435 

#**Summary of Findings**: 
# No difference in any of the gut health markers between secretors and non-secretors


```


